version: '{build}'

# Source Config

clone_folder: c:\gopath\src\github.com\netlify\open-api

# Build host

environment:
  GOPATH: c:\gopath
  DEPTESTBYPASS501: 1
  GOVERSION: 1.10

init:
  - git config --global core.autocrlf input

# Build

install:
  # Install the specific Go version.
  - rmdir c:\go /s /q
  - appveyor DownloadFile https://storage.googleapis.com/golang/go%GOVERSION%.windows-amd64.msi
  - msiexec /i go%GOVERSION%.windows-amd64.msi /q
  - set Path=c:\go\bin;c:\gopath\bin;C:\Program Files (x86)\Bazaar\;C:\Program Files\Mercurial\%Path%
  - go version
  - go env
  - go get -u github.com/golang/dep/cmd/dep
  - ps: cd go
  - dep ensure

build: false
deploy: false

test_script:
  - go test -v github.com/netlify/open-api/...
