name: swagger-bump
on:
  # Workaround for bumping the swagger.yml file on release-please PRs
  push:
    branches:
      - release-*
jobs:
  swagger-bump:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '*'
          check-latest: true
          registry-url: 'https://registry.npmjs.org'
      - run: npm run bump-swagger
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'chore: bump swagger.yml file'
