name: swagger-bump
on:
  push:
    branches:
      - release-*
jobs:
  swagger-bump:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: 'https://registry.npmjs.org'
      - run: npm install
      - run: npm version:1-swagger
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Bump swagger.yml file"
