name: Verify Go client

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  verify-go:
    name: Verify go client source code is up to date
    strategy:
      matrix:
        os: [ubuntu-latest]
        go_version: [1.15.x]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Install Go ${{ matrix.go }}
        uses: actions/setup-go@v2.1.3
        with:
          go-version: ${{ matrix.go_version }}
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: make all
      - name: Check for changes
        run: |
          if [ -z "$(git status --porcelain)" ]; then
            echo "No changes to the go client source files detected"
          else
            echo "Changes to the go client source files detected, please run 'make all' and push your changes"
            exit 1
          fi
